/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment6;

public class App {

    public static void main(String[] args) {
        int numLoops = 5;  // number of times each task loops

        System.out.println("Starting DemoReentrantLock...");
        DemoReentrantLock.showReentrantLock(numLoops);
        System.out.println("DemoReentrantLock finished.");

        System.out.println("Starting ReadWriteLock demo...");
        DemoReadWriteLock.showReadWriteLock(args);
        System.out.println("ReadWriteLock demo finished.");
        
    }
}
