/*
 * This source file was generated by the Gradle 'init' task
 */
package assignment6;

import org.junit.jupiter.api.Test;
import java.time.Duration;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void showReentrantLock_completesQuickly() {
        assertTimeoutPreemptively(Duration.ofSeconds(5), () -> {
            DemoReentrantLock.showReentrantLock(5);
        });
    }

    @Test
    void showReadWriteLock_completesQuickly() {
        assertTimeoutPreemptively(Duration.ofSeconds(2), () -> {
            DemoReadWriteLock.showReadWriteLock(new String[0]);
        });
    }

    @Test
    void showReadWriteLock_doesNotThrowException() {
        assertDoesNotThrow(() -> DemoReadWriteLock.showReadWriteLock(new String[0]));
    }
}
