/*
 * This source file was generated by the Gradle 'init' task
 */
package th5;


public class App {
    int iy = 10;
    final int iz = 15;

    public static void main(String[] args) {
        App app = new App();
        app.iy = 20;
        // This line produces a compile error
        // app.iz = 11;
    }
}
