/*
 * This source file was generated by the Gradle 'init' task
 */
package th5;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
  @Test void testReentrantLock() {
    try {
       DemoReentrantLock.showReentrantLock(5);
       assertTrue(true);
    } catch (Exception e) {
      e.printStackTrace();
      fail(e.getMessage());
    }  
  } 
  @Test void testReadWriteLock() {
    try {
       DemoReadWriteLock.showReadWriteLock(null);
       assertTrue(true);
    } catch (Exception e) {
      e.printStackTrace();
      fail(e.getMessage());
    }  
  }
}
